### ISSUE TITLE
Fields name issue in docs

### ISSUE THREAD

**Issue by icastillejogomez** [intrinio/javascript-sdk#6]
If you read this doc: https://github.com/intrinio/javascript-sdk/blob/master/docs/ApiResponseStandardizedFinancials.md

Fields are camelcase but answer is not camel case. For example: nextPage is next_page in server answer payload. standardizedFinancials is standardized_financials in server answer.

**Comment by kgmiller** [comment]
Our API v2 responses are (unless otherwise specified) in JSON format with snake_case object / property names. There is currently no documented JSON convention with regards to object / property names. Many languages generate JSON, so, it makes sense that there is no hard convention. Internally, snake_case is our API development convention given the languages we use development. That said, the conventional naming scheme for Javascript is CamelCase - so, our Javascript SDK uses CamelCase for objects and properties in accordance with conventions, even though the API responses themselves are in snake_case. If we were to switch our API response conventions, we'd simply be creating this same issue for Ruby and Python SDK developers ;) - hope that helps explain.
